<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "powermail_encryption"
 *
 * Auto generated by Extension Builder 2018-10-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Powermail Encryption',
	'description' => '',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '',
	'constraints' => [
     	'depends' => [
         	'typo3' => '7.6.1-8.99.99',
        	 'php' => '5.5.0-7.99.99',
			 'powermail' => '*'
     	],
     	'conflicts' => [
        	 'compatibility6' => '7.6.0-7.6.99'
     	],
    	 'suggests' => [],
 	]
);